version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - pip install -r requirements/common.txt

  

artifacts:
  type: zip
  files:
    - 'template.yml'
    - 'ec2django/**/*'
    - 'helloworld/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
    - 'manage.py'
    - 'requirements/**/*'
    - 'requirements.txt'
    - 'supervisord.conf'
